platform :ios, '7.0'
pod 'AFNetworking', '~> 2.2.4'
pod 'AFNetworking-MUResponseSerializer', '~> 1.0.0'
pod 'NSObject-MUJSONMapping', '~> 1.0.0'
pod 'AFNetworking2-RACExtensions', '~> 0.0.1'
pod 'ReactiveCocoa', '~> 2.3'
pod 'ReactiveViewModel', '~> 0.2'
pod 'CocoaAsyncSocket', '~> 7.3.5'
pod 'XMPPFramework', '~> 3.6.4'
pod 'MBProgressHUD', '~> 0.8'
pod 'HPGrowingTextView', '~> 1.1'
pod 'QBImagePickerController', '~> 2.1'
pod 'SDWebImage', '~> 3.6'